services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - PUID=1000   # Adjust these IDs if needed to match the user/group IDs on your OpenMediaVault server
      - PGID=100
    volumes:
      - /srv/dev-disk-by-uuid-720cfb7f-b874-45a8-8232-d6e97c0f124a/shared/Jellyfin/config:/config
      - /srv/dev-disk-by-uuid-720cfb7f-b874-45a8-8232-d6e97c0f124a/shared/Jellyfin/media:/media

