services:
  unbound:
    image: nl5187/unbound:latest # Use a suitable Unbound Docker image
    container_name: unbound
    restart: unless-stopped
    networks:
      ph_network:
        ipv4_address: 192.168.1.64
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf
      - unbound_data:/var/lib/unbound
    command: ["-d", "-v"]

networks:
  ph_network:
    external: true

volumes:
  unbound_data:

